# Generated by Django 4.2.4 on 2023-08-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
