# Generated by Django 4.2.4 on 2023-08-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_address_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.address'),
        ),
    ]
