# Generated by Django 4.0 on 2023-09-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggestion',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
